apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-deploy
  name: vault-deploy
  namespace: worldskills
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: vault-deploy
    spec:
      containers:
      - image: vault
        name: vault
        ports:
        - containerPort: 8200
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
status: {}
