apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-deploy
  name: vault-deploy
  namespace: worldskills
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-deploy
  template:
    metadata:
      labels:
        app: vault-deploy
    spec:
      containers:
        - name: vault
          image: hashicorp/vault
          command:
            - "vault"
            - "server"
            - "-dev"
            - "-dev-root-token-id=root"
            - "-dev-listen-address=0.0.0.0:8200"
          ports:
            - containerPort: 8200
          securityContext:
            runAsUser: 0
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

