apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scaledobject
  namespace: worldskills
spec:
  minReplicaCount: 3
  maxReplicaCount: 6
  scaleTargetRef:
    name: nginx-deploy
  triggers:
  - type: cpu
    metricType: Utilization 
    metadata:
      value: "50"
